spring:
  profiles:
    active: test

mybatis:
  mapper-locations: classpath*:com/ljf/sidanfinance/dao/mapping/*Mapper.xml
  type-aliases-package: com.ljf.sidanfinance.dao.model
#  configuration:
#      map-underscore-to-camel-case: true

logging:
  path: ./logs/sidanfinance.log
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm} [%thread] %-5level %logger: %msg%n"
#    %d{HH:mm:ss.SSS}——日志输出时间
#    %thread——输出日志的进程名字，这在Web应用以及异步任务处理中很有用
#    %-5level——日志级别，并且使用5个字符靠左对齐
#    %logger- ——日志输出者的名字
#    %msg——日志消息
#    %n——平台的换行符


mapper:
  mappers: com.ljf.sidanfinance.dao.base.BaseMapper
  not-empty: false
  identity: MYSQL