#server
server:
  port: 8888
#  servlet:
#    context-path: /cwebe

#spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.109.84:3306/sidan_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://49.235.109.84:3306/sidan_finance?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: ljf92219
    type: com.alibaba.druid.pool.DruidDataSource
#  resources:
#    static-locations: [
#      "classpath:test1",
#      "classpath:test2"
#    ]
#  mvc:
#    view:
#      prefix: classpath:static
#      suffix: .html
